spring.application.name=demo

springdoc.api-docs.enabled = true
springdoc.swagger.ui.enabled = true
springdoc.swagger-ui.path=/doc/swagger-vi.html
server.servlet.context-path=/api/v1
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://database-1.cd4su4egkj8x.us-east-2.rds.amazonaws.com:3306/ayd2a
spring.datasource.username=admin
spring.datasource.password=root12345

#CONFIGURACION JWT
security.jwt.secret=SCRET_KEY_AYD2_CUNO-USAC.EXAMPLE
security.jwt.expiration-seconds=5600

#CONFIGURACION EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jhony.fuentes19@gmail.com
spring.mail.password=mhnn bfgb vwyn xkup  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


aws.s3.bucket-name=seminario1datos
aws.s3.region=us-east-2
aws.s3.access-key=AKIAWYFMPYTX6BDRBW6V
aws.s3.user-id: frontend
aws.s3.secret-key= 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